fun main () {

    val service = NoteService()
    val note1 = Note(1,"1","1")
    service.addNote(note1)
    //val note2 = Note(2,"2","2")
    //service.addNote(note2)
    val comment1 = Comment(1,1,"1")
    service.addComment(1,comment1)
    //val comment2 = Comment(2,2,"2")
    //service.addComment(2,comment2)
    println(note1.editComment(1,"2"))
   // println(service.addNote(note1))
   // println(service.addNote(note2))
   // println(service.list.size)
   // println(service.list[0])
    //println(service.list[1])
   // println(service.getNote(1))
   // println(service.deleteNote(note2))
   // println(service.getNote(2))
    //println(service.updateNote(note1))
   // println(service.getNote(1))
   // println(note1.getAllComments())
    //println(note1.deleteComment(1))
   // println(note1.getAllComments())
    //println(note1.restoreComment(1))
    //println(note1.getAllComments())
}